#!/bin/sh
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2010 Oracle and/or its affiliates. All rights reserved.
#
# Use is subject to License Terms
#

"/home/student/projekt2/tje2/scripts/glassfish3/glassfish/bin/asadmin" start-domain domain1
#!/bin/sh
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2010 Oracle and/or its affiliates. All rights reserved.
#
# Use is subject to License Terms
#

"/home/student/projekt2/tje2/scripts/glassfish3/glassfish/bin/asadmin" start-domain domain1
